### ISSUE TITLE
Laravel @php Helper

### ISSUE THREAD

**Issue by HDVinnie** [shufo/blade-formatter#3]
Instead of just removing code like `@php $bg = rand(1, 13); $bgchange = $bg.".jpg"; @endphp` from a view wouldn't it be better to just throw a warning that using `@php` tag in views is frowned upon to avoid breaking views?

**Comment by HDVinnie** [comment]
@shufo any update?

**Comment by shufo** [comment]
@HDVinnie 
Sorry for late reply!
`@php` and `@endphp` are currently supported in blade-formatter but php code inside it will not be formatted. 
So be careful if you use `@php` and `@endphp`. 
Move raw php code to above interface like controller would be better result I suppose.

**Comment by HDVinnie** [comment]
I dont see how its supported when it completely strips any `@php @endphp` and the code within it.

**Comment by vielhuber** [comment]
Same here. Please leave the php content inside available; I just unintentionally broke my template.

**Comment by shufo** [comment]
@HDVinnie 
Uh sorry I just realised what is the problem.

Inline `@php ~ @endphp` code break the php code within it like 

```php
<div class="pf-users-branch">
    @php $bg = rand(1, 13); $bgchange = $bg.".jpg"; @endphp
</div>
```

into 

```php
<div class="pf-users-branch">
</div>
```

But block level `@php` ~ `@endphp` code like below did'nt break the code within it.

```php
            <div class="pf-users-branch">
                @php
                    $bg = rand(1, 13); $bgchange = $bg.".jpg";
                @endphp
            </div>
``` 

will be formatted into 

```php
            <div class="pf-users-branch">
                @php
                $bg = rand(1, 13); $bgchange = $bg.".jpg";
                @endphp
            </div>
```

I mean currently its supported in this usage.

So please consider to use block level statement if you use `@php ~ @endphp` at this time.
I'll fix this in next release!

**Comment by shufo** [comment]
Fixed this issue in 1.1.3
https://www.npmjs.com/package/blade-formatter/v/1.1.3

**Comment by vielhuber** [comment]
Thanks for the fix. The formatting is still not correct:

Input:
```
@section('content')
    <div class="content-header">
        <div>@php echo 'FOO'; @endphp</div>
    </div>    
    <div>@php echo 'FOO'; @endphp</div>
@endsection
```

Expected:
```
@section('content')
    <div class="content-header">
        <div>@php echo 'FOO'; @endphp</div>
    </div>    
    <div>@php echo 'FOO'; @endphp</div>
@endsection
```

Real output:
```
@section('content')
    <div class="content-header">
    <div>@php echo 'FOO'; @endphp</div>
    </div>
<div>@php echo 'FOO'; @endphp</div>
@endsection
```

**Comment by shufo** [comment]
@vielhuber 
ok confirmed that problem and published fixed version with 1.1.4.
https://www.npmjs.com/package/blade-formatter/v/1.1.4
