### ISSUE TITLE
syntax error with @include

### ISSUE THREAD

**Issue by G3z** [shufo/blade-formatter#504]
Laravel 9, PHP 8.1
#502 introduced a bug

`@include('livewire.cx.equipment-list-internal.account', ['account' => $account])`
has been formatted as
```
@include(
    'livewire.cx.equipment-list-internal.account', 
    ['account' => $account],
)
```
notice the last comma after `]`
and this throws `syntax error, unexpected token ",", expecting ")"`

**Comment by shufo** [comment]
Thanks @G3z!
Fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.20.3

**Comment by mrtawil** [comment]
Hello guys, thanks for the fast support. I have installed the new extension version `v1.20.3` but I am still facing the same issue with the following code of line:

`@include('adminro::includes.dashboard.datatables.datatable_forms', ['controllerSettings' => $controllerSettings, 'dataTable' => $dataTable])`

I will be very thankful if you fixed this size too or provide me with a suitable workaround.

**Comment by shufo** [comment]
Hi @mrtawil 

Does this still cause a syntax error exception?

```blade
@include(
    'adminro::includes.dashboard.datatables.datatable_forms',
    ['controllerSettings' => $controllerSettings, 'dataTable' => $dataTable]
)
```

If it's a matter of preference for newlines, https://github.com/shufo/blade-formatter/releases/tag/v1.20.4 takes into respect of wrap line length, so you can adjust the behavior with the `wrapLineLength` option.

```blade
$ blade-formatter example.blade.php --wrap 200
---
# =>
@include('adminro::includes.dashboard.datatables.datatable_forms', ['controllerSettings' => $controllerSettings, 'dataTable' => $dataTable])

$ blade-formatter example.blade.php --wrap 150
# =>
@include('adminro::includes.dashboard.datatables.datatable_forms', [
    'controllerSettings' => $controllerSettings,
    'dataTable' => $dataTable,
])
```

`.bladeformatterrc.json`

```json
{
  "wrapLineLength": 150
}
```

**Comment by mrtawil** [comment]
Hello @shufo,

Thanks for your reply.

I am using the plugin in vs-code and I am still having the same issue even after I have set `wrapLineLength` property 200 or even 10000.

**Comment by shufo** [comment]
@mrtawil 
Thanks, I'm glad you started like Blade's coding!

By the way, in my environment, the following code which contains newlines does not seem to cause an Exception.

```blade
@include(
    'adminro.dashboard.datatables.datatable_forms',
    ['controllerSettings' => $controllerSettings, 'dataTable' => $dataTable]
)
```

Can you provide minimum reproduceable repository or something? Or a screenshot or screencast reproducing the situation would be appreciated!
